### ISSUE TITLE
Installation on Ubuntu 20.x

### ISSUE THREAD

**Issue by cnvo** [j0k3r/f43.me#456]
In requirements, you'll also need to install Ruby `sudo apt install ruby-full`
Then run this command `gem update --system && gem install compass`

Otherwise you'll have errors while trying to run this command `./node_modules/gulp/bin/gulp.js`

I hope this helps anyone else!

**Comment by cnvo** [comment]
Additionally you might run into another issue while running this command `SYMFONY_ENV=prod composer install -o --no-dev`, actually you'll need to remove the `--no-dev` part for now for this to work as well.

**Comment by j0k3r** [comment]
I'll update the readme accordingly.
What error did you get with composer with the parameter `--no-dev`?

**Comment by cnvo** [comment]
https://github.com/doctrine/DoctrineFixturesBundle/issues/71

**Comment by cnvo** [comment]
So I modified it to this

```
{
    "name": "j0k3r/f43.me",
    "description": "A More readable & cleaner feed",
    "license": "MIT",
    "type": "project",
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "authors": [
        {
            "name": "Jeremy Benoist",
            "email": "jeremy.benoist@gmail.com",
            "homepage": "http://www.j0k3r.net",
            "role": "Developer"
        }
    ],
    "require": {
        "php": "^7.2.9",
        "beberlei/doctrineextensions": "^1.2",
        "composer/package-versions-deprecated": "^1.11",
        "custom-zurb/foundation": "4.3.2",
        "doctrine/doctrine-bundle": "^2.0",
        "doctrine/orm": "^2.5",
        "j0k3r/graby": "^2.0",
        "j0k3r/php-imgur-api-client": "~3.0",
        "laminas/laminas-code": "^3.4",
        "mnsami/composer-custom-directory-installer": "~2.0",
        "php-http/guzzle6-adapter": "^2.0",
        "php-http/httplug-bundle": "^1.14",
        "ricardoper/twitteroauth": "~1.0",
        "sensio/framework-extra-bundle": "^5.6",
        "sentry/sentry-symfony": "^3.0",
        "simplepie/simplepie": "~1.4",
        "stof/doctrine-extensions-bundle": "~1.1",
        "symfony/amqp-messenger": "5.1.*",
        "symfony/asset": "5.1.*",
        "symfony/dotenv": "5.1.*",
        "symfony/flex": "^1.9",
        "symfony/form": "5.1.*",
        "symfony/lock": "5.1.*",
        "symfony/messenger": "5.1.*",
        "symfony/monolog-bundle": "^3.5",
        "symfony/security-bundle": "5.1.*",
        "symfony/translation": "5.1.*",
        "symfony/twig-bundle": "5.1.*",
        "symfony/validator": "5.1.*",
        "symfony/yaml": "5.1.*",
        "twig/extra-bundle": "^2.12|^3.0",
        "twig/twig": "^2.12|^3.0"
    },
    "require-dev": {
        "doctrine/doctrine-fixtures-bundle": "^3.3",
        "friendsofphp/php-cs-fixer": "~2.0",
        "php-http/mock-client": "^1.3",
        "phpstan/extension-installer": "^1.0",
        "phpstan/phpstan": "^0.12",
        "phpstan/phpstan-deprecation-rules": "^0.12.5",
        "phpstan/phpstan-doctrine": "^0.12",
        "phpstan/phpstan-phpunit": "^0.12",
        "phpstan/phpstan-symfony": "^0.12",
        "symfony/browser-kit": "5.1.*",
        "symfony/css-selector": "5.1.*",
        "symfony/debug-bundle": "5.1.*",
        "symfony/maker-bundle": "^1.21",
        "symfony/phpunit-bridge": "5.1.*",
        "symfony/stopwatch": "5.1.*",
        "symfony/web-profiler-bundle": "5.1.*"
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "scripts": {
        "preinstall": "npx npm-force-resolutions",
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ],
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
    },
    "config": {
        "platform": {
            "php": "7.2.9"
        },
        "bin-dir": "bin",
        "sort-packages": true
    },
    "extra": {
        "installer-paths": {
            "./templates/lib/foundation/": [
                "custom-zurb/foundation"
            ]
        },
        "symfony": {
            "allow-contrib": true,
            "require": "5.1.*"
        }
    },
    "resolutions": {
        "graceful-fs": "^4.2.4"
    },
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "custom-zurb/foundation",
                "version": "4.3.2",
                "dist": {
                    "url": "https://wildtrip.s3-eu-west-1.amazonaws.com/foundation-sites-4.3.2.zip",
                    "type": "zip"
                }
            }
        }
    ]
}

```

**Comment by j0k3r** [comment]
> `Class 'Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle' not found`

Strange. Did you still have the output of the composer install? Just wondering when did that happen.

> So I modified the composer.json to this

Changes are only related to js stuff, not php related 🤔
![image](https://user-images.githubusercontent.com/62333/98090033-d2232600-1e83-11eb-8eab-78f72de21f56.png)

**Comment by cnvo** [comment]
I removed it because it was irrelevant. 

But here's the output for composer related error:

```
root@unknown:/gopanel/sites/f43.me# SYMFONY_ENV=prod composer install -o --no-dev
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 124 installs, 0 updates, 0 removals
  - Installing composer/package-versions-deprecated (1.11.99): Loading from cache
  - Installing mnsami/composer-custom-directory-installer (2.0.0): Loading from cache
  - Installing symfony/flex (v1.9.10): Loading from cache
  - Installing symfony/polyfill-php80 (v1.20.0): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.20.0): Loading from cache
  - Installing symfony/polyfill-intl-normalizer (v1.20.0): Loading from cache
  - Installing symfony/polyfill-intl-grapheme (v1.20.0): Loading from cache
  - Installing symfony/polyfill-ctype (v1.20.0): Loading from cache
  - Installing symfony/string (v5.1.8): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing symfony/service-contracts (v2.2.0): Loading from cache
  - Installing symfony/polyfill-php73 (v1.20.0): Loading from cache
  - Installing symfony/console (v5.1.8): Loading from cache
  - Installing doctrine/event-manager (1.1.1): Loading from cache
  - Installing doctrine/collections (1.6.7): Loading from cache
  - Installing doctrine/cache (1.10.2): Loading from cache
  - Installing doctrine/lexer (1.2.1): Loading from cache
  - Installing doctrine/annotations (1.11.1): Loading from cache
  - Installing doctrine/persistence (2.1.0): Loading from cache
  - Installing doctrine/instantiator (1.3.1): Loading from cache
  - Installing doctrine/inflector (1.4.3): Loading from cache
  - Installing doctrine/dbal (2.10.4): Loading from cache
  - Installing doctrine/common (3.0.2): Loading from cache
  - Installing doctrine/orm (2.7.4): Loading from cache
  - Installing beberlei/doctrineextensions (v1.2.9): Downloading (100%)         
  - Installing behat/transliterator (v1.3.0): Loading from cache
  - Installing clue/stream-filter (v1.5.0): Loading from cache
  - Installing custom-zurb/foundation (4.3.2): Loading from cache
  - Installing symfony/deprecation-contracts (v2.2.0): Loading from cache
  - Installing symfony/routing (v5.1.8): Loading from cache
  - Installing symfony/http-foundation (v5.1.8): Loading from cache
  - Installing symfony/http-client-contracts (v2.3.1): Loading from cache
  - Installing psr/event-dispatcher (1.0.0): Loading from cache
  - Installing symfony/event-dispatcher-contracts (v2.2.0): Loading from cache
  - Installing symfony/event-dispatcher (v5.1.8): Loading from cache
  - Installing symfony/var-dumper (v5.1.8): Loading from cache
  - Installing psr/log (1.1.3): Loading from cache
  - Installing symfony/error-handler (v5.1.8): Loading from cache
  - Installing symfony/http-kernel (v5.1.8): Loading from cache
  - Installing symfony/finder (v5.1.8): Loading from cache
  - Installing symfony/filesystem (v5.1.8): Loading from cache
  - Installing symfony/dependency-injection (v5.1.8): Loading from cache
  - Installing symfony/config (v5.1.8): Loading from cache
  - Installing symfony/var-exporter (v5.1.8): Loading from cache
  - Installing psr/cache (1.0.1): Loading from cache
  - Installing symfony/cache-contracts (v2.2.0): Loading from cache
  - Installing symfony/cache (v5.1.8): Loading from cache
  - Installing symfony/framework-bundle (v5.1.8): Loading from cache
  - Installing symfony/doctrine-bridge (v5.1.8): Loading from cache
  - Installing doctrine/sql-formatter (1.1.1): Loading from cache
  - Installing doctrine/doctrine-bundle (2.1.2): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing psr/http-factory (1.0.1): Loading from cache
  - Installing ralouphie/getallheaders (3.0.3): Loading from cache
  - Installing guzzlehttp/psr7 (1.7.0): Loading from cache
  - Installing http-interop/http-factory-guzzle (1.0.0): Loading from cache
  - Installing true/punycode (v2.1.1): Loading from cache
  - Installing symfony/options-resolver (v5.1.8): Loading from cache
  - Installing smalot/pdfparser (v0.16.2): Loading from cache
  - Installing simplepie/simplepie (1.5.6): Loading from cache
  - Installing php-http/message-factory (v1.0.2): Loading from cache
  - Installing php-http/message (1.9.1): Loading from cache
  - Installing psr/http-client (1.0.1): Loading from cache
  - Installing php-http/promise (1.1.0): Loading from cache
  - Installing php-http/httplug (2.2.0): Loading from cache
  - Installing php-http/discovery (1.12.0): Loading from cache
  - Installing php-http/client-common (2.3.0): Loading from cache
  - Installing monolog/monolog (2.1.1): Loading from cache
  - Installing masterminds/html5 (2.7.4): Loading from cache
  - Installing j0k3r/php-readability (1.2.5): Loading from cache
  - Installing j0k3r/httplug-ssrf-plugin (v2.0.2): Loading from cache
  - Installing j0k3r/graby-site-config (1.0.117): Loading from cache
  - Installing fossar/htmlawed (1.2.7): Loading from cache
  - Installing j0k3r/graby (v2.2.2): Loading from cache
  - Installing symfony/polyfill-php72 (v1.20.0): Loading from cache
  - Installing symfony/polyfill-intl-idn (v1.20.0): Loading from cache
  - Installing guzzlehttp/promises (1.4.0): Loading from cache
  - Installing guzzlehttp/guzzle (6.5.5): Loading from cache
  - Installing j0k3r/php-imgur-api-client (3.0.3): Loading from cache
  - Installing laminas/laminas-zendframework-bridge (1.1.1): Loading from cache
  - Installing laminas/laminas-eventmanager (3.2.1): Loading from cache
  - Installing laminas/laminas-code (3.4.1): Loading from cache
  - Installing symfony/stopwatch (v5.1.8): Loading from cache
  - Installing php-http/stopwatch-plugin (1.3.0): Loading from cache
  - Installing php-http/logger-plugin (1.2.0): Loading from cache
  - Installing symfony/http-client (v5.1.8): Loading from cache
  - Installing php-http/guzzle6-adapter (v2.0.1): Loading from cache
  - Installing php-http/httplug-bundle (1.19.0): Loading from cache
  - Installing ricardoper/twitteroauth (v1.1.1): Loading from cache
  - Installing sensio/framework-extra-bundle (v5.6.1): Loading from cache
  - Installing symfony/polyfill-uuid (v1.20.0): Loading from cache
  - Installing jean85/pretty-package-versions (1.5.1): Loading from cache
  - Installing sentry/sentry (2.5.0): Loading from cache
  - Installing symfony/security-core (v5.1.8): Loading from cache
  - Installing sentry/sdk (2.2.0)
  - Installing sentry/sentry-symfony (3.5.3): Loading from cache
  - Installing gedmo/doctrine-extensions (v3.0.0): Loading from cache
  - Installing stof/doctrine-extensions-bundle (v1.5.0): Loading from cache
  - Installing symfony/messenger (v5.1.8): Loading from cache
  - Installing symfony/redis-messenger (v5.1.8): Loading from cache
  - Installing symfony/doctrine-messenger (v5.1.8): Loading from cache
  - Installing symfony/amqp-messenger (v5.1.8): Loading from cache
  - Installing symfony/asset (v5.1.8): Loading from cache
  - Installing symfony/dotenv (v5.1.8): Loading from cache
  - Installing symfony/property-info (v5.1.8): Loading from cache
  - Installing symfony/property-access (v5.1.8): Loading from cache
  - Installing symfony/intl (v5.1.8): Loading from cache
  - Installing symfony/polyfill-intl-icu (v1.20.0): Loading from cache
  - Installing symfony/form (v5.1.8): Loading from cache
  - Installing symfony/lock (v5.1.8): Loading from cache
  - Installing symfony/monolog-bridge (v5.1.8): Loading from cache
  - Installing symfony/monolog-bundle (v3.6.0): Loading from cache
  - Installing symfony/security-http (v5.1.8): Loading from cache
  - Installing symfony/security-guard (v5.1.8): Loading from cache
  - Installing symfony/security-csrf (v5.1.8): Loading from cache
  - Installing symfony/security-bundle (v5.1.8): Loading from cache
  - Installing symfony/translation-contracts (v2.3.0): Loading from cache
  - Installing symfony/translation (v5.1.8): Loading from cache
  - Installing twig/twig (v3.1.1): Loading from cache
  - Installing symfony/twig-bridge (v5.1.8): Loading from cache
  - Installing symfony/validator (v5.1.8): Loading from cache
  - Installing symfony/yaml (v5.1.8): Loading from cache
  - Installing symfony/twig-bundle (v5.1.8): Loading from cache
  - Installing twig/extra-bundle (v3.1.1): Loading from cache
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
76 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Run composer recipes at any time to see the status of your Symfony recipes.

Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  Symfony\Component\ErrorHandler\Error\ClassNotFoundError {#67
!!    #message: """
!!      Attempted to load class "DoctrineFixturesBundle" from namespace "Doctrine\Bundle\FixturesBundle".\n
!!      Did you forget a "use" statement for another namespace?
!!      """
!!    #code: 0
!!    #file: "./vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php"
!!    #line: 74
!!    trace: {
!!      ./vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php:74 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:371 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:128 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:168 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:74 { …}
!!      ./vendor/symfony/console/Application.php:142 { …}
!!      ./bin/console:43 {
!!        › $application = new Application($kernel);
!!        › $application->run($input);
!!        › 
!!      }
!!    }
!!  }
!!  2020-11-04T05:30:41+00:00 [critical] Uncaught Error: Class 'Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle' not found
!!  
Script @auto-scripts was called via post-install-cmd
```


Also I see that you cannot use Node 12x. I downgraded to Node10, otherwise you'll get this error:

```
./node_modules/gulp/bin/gulp.js
fs.js:36
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:36:5
    at req_ (/gopanel/sites/f43.me/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/gopanel/sites/f43.me/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/gopanel/sites/f43.me/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)

```

**Comment by j0k3r** [comment]
> But here's the output for composer related error:

In fact, the README isn't up to date since I jumped to Symfony 5.
Instead of `SYMFONY_ENV=prod` before the composer command you should use `ENV=prod`. The error should disappear.

> Also I see that you cannot use Node 12x. I downgraded to Node10, otherwise you'll get this error:

As stated in the [`.nvmrc`](https://github.com/j0k3r/f43.me/blob/master/.nvmrc), the working version of Node is 0.12.2

**Comment by cnvo** [comment]
Ah... I see now. 

Thanks for the clarification!

**Comment by j0k3r** [comment]
The whole project has been updated with Node 16.
Are you still seeing issues?
